services:
  bot:
    build: .
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/ebanez
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=ebanez
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'

volumes:
  mongodb_data:
